# version: "3.9"

# services:
#   postgres:
#     image: postgres:16-alpine
#     container_name: school-id-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: school_id
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


# version: "3.9"

# services:
#   postgres:
#     image: postgres:16-alpine
#     container_name: school-id-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: school_id
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   backend:
#     build: .
#     container_name: school-id-backend
#     restart: always
#     ports:
#       - "5000:5000"
#     env_file:
#       - .env
#     depends_on:
#       - postgres

# volumes:
#   postgres_data:


version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: school-id-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_id
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: school-id-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    # volumes:
    #   - .:/app   # 🔥 THIS LINE FIXES EVERYTHING

volumes:
  postgres_data:
